In [4]:
#1. create an array
import numpy as np
x=np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
#2. array operations
a=np.array([10,20,30,40,50])
b=np.array([1,2,3,4,5])
print(f'Addition={a+b}')
print(f'Subtraction={a-b}')
print(f'Multiplication={a*b}')
print(f'Division={a/b}')


Addition=[11 22 33 44 55]
Subtraction=[ 9 18 27 36 45]
Multiplication=[ 10  40  90 160 250]
Division=[10. 10. 10. 10. 10.]


In [18]:
#3. find maximum and minimum
marks=np.array([85,72,91,65,78,88])
print('Maximum mark=',np.max(marks))

Maximum mark= 91


In [17]:
print('Minimum mark=',np.min(marks))

Minimum mark= 65


In [22]:
print('Average mark=',np.average(marks))

Average mark= 79.83333333333333


In [28]:
#4. even numbers
import numpy as np
a=np.arange(1,21)
x=np.where(a%2==0)
for i in x:
    for j in i:
        print(a[j])

2
4
6
8
10
12
14
16
18
20


In [38]:
#5. reshape an array
a=np.arange(1,13)
b=a.reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
