In [3]:
#1. create and reshape an array
import numpy as np
array=np.arange(1,21)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [4]:
matrix=array.reshape(4,5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
matrix.shape

(4, 5)

In [8]:
matrix.ndim

2

In [6]:
#2. array statistics
marks=np.array([78,85,92,67,88,95,72,81,90,76])
print('mean=',np.mean(marks))
print('median=',np.median(marks))
print('maximum=',np.max(marks))
print('minimum=',np.min(marks))

mean= 82.4
median= 83.0
maximum= 95
minimum= 67


In [6]:
#3. matrix operations
import numpy as np
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
B=np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])
print('Addition=',(A+B))
print('Subtraction=',(A-B))
print('Element-wise multiplication=',(A*B))

Addition= [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction= [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Element-wise multiplication= [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [7]:
#4. real world sales analysis
import numpy as np
sales=np.array([
    12000,15000,18000,14000,
    22000,25000,21000,19000,
    28000,30000,27000,32000
])
months=['january','february','march','april','may','june','july','august','september','october','november','december']
print('total sales=',np.sum(sales))
print('average sales=',np.mean(sales))
print('highest sales month=',months[np.argmax(sales)])
print('lowest sales month=',months[np.argmin(sales)])

total sales= 263000
average sales= 21916.666666666668
highest sales month= december
lowest sales month= january
